__title__ = "billzio_api"
__description__ = "Python wrapper for Billz.io Public API"
__version__ = "1.0.4"
__author__ = "Sirojiddin Mustafayev"
__author_email__ = "sirojiddinmustafayev@gmail.com"
__license__ = "Apache 2.0"
__copyright__ = "Copyright Sirojiddin Mustafayev"
